**21st May 2026**

**Libraries:** They are collection of modules and fuctions to perform the specific tasks

**Data Analysis**
* pandas: data manipulation
* numPy (numerical python): multi-dimensional arrays and mathematical operations
* matplotlib, seaborn, plotly: data visualization
* statistics 

**Machine learning**
* sklearn (scikit learn): machine learning

**Deep Learning:**
* keras: deep learning
* tensorflow: google
* pytorch: Facebook

**pandas:** Data Manipulation

* Series data: 1D data (single column)
* Dataframe data: 2D data (table)

In [1]:
import pandas as pd

In [3]:
s1 = pd.Series([2,5,4,8,8,1,0])
s1

0    2
1    5
2    4
3    8
4    8
5    1
6    0
dtype: int64

In [4]:
#create dictionary for the 4 emp details
#eid,ename,dept,salary
employee_data = {
    "eid": [101, 102, 103, 104],
    "ename": ["Kavya", "Aishwarya", "Nisarga", "Meghana"],
    "dept": ["Sales", "Marketing", "Engineering", "HR"],
    "salary": [60000, 70000, 80000, 55000]
}
print(employee_data)

{'eid': [101, 102, 103, 104], 'ename': ['Kavya', 'Aishwarya', 'Nisarga', 'Meghana'], 'dept': ['Sales', 'Marketing', 'Engineering', 'HR'], 'salary': [60000, 70000, 80000, 55000]}

In [5]:
d1 = pd.DataFrame(employee_data)
d1

   eid      ename         dept  salary
0  101      Kavya        Sales   60000
1  102  Aishwarya    Marketing   70000
2  103    Nisarga  Engineering   80000
3  104    Meghana           HR   55000

In [6]:
emp=pd.read_excel("emp_data.xlsx")
emp

   eid ename   sal  dept
0    1    aa  1234    10
1    2    bb  2345    20
2    3    cc  3214    30
3    4    dd  5332    40

In [3]:
cars=pd.read_csv("mtcars.csv")
cars

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [10]:
stu=pd.read_csv("studata.txt")
stu

   sid    sname            emialid address  phoneno
0    1    priya    priya@gmail.com     dvg     9876
1    2  karthik  karthik@gmail.com     blr    12345
2    3    karan                NaN     msr    34567

In [11]:
cpl=pd.read_table("chipotle.tsv")
cpl

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [12]:
cpls = pd.read_csv("chipotle.tsv", sep='\t')
cpls

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

**22nd May 2026**

In [33]:
cars

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,half_qsec
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,8.230
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,8.510
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,9.305
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,9.720
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,8.510
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,10.110
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,7.920
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,10.000
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,11.450
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,9.150
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,9.450
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,8.700
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,8.800
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,9.000
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,8.990
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,8.910
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,8.710
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,9.735
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,9.260
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,9.950
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,10.005
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8.435
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,8.650
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,7.705
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,8.525
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,9.450
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8.350
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,8.450
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,7.250
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,7.750
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,7.300
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,9.300

In [14]:
cars.shape #shape gives the number of rows and columns

(32, 12)

In [15]:
cars.shape[0] #gives the row count

32

In [16]:
cars.shape[1] #it gives the column count

12

In [17]:
cars.columns #gives the column names

Index(['manufacturer', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [18]:
cars.dtypes #it gives the column names with there datatype

manufacturer     object
mpg             float64
cyl               int64
disp            float64
hp                int64
drat            float64
wt              float64
qsec            float64
vs                int64
am                int64
gear              int64
carb              int64
dtype: object

In [20]:
cars.isna() #shows the null values, False- value is present True- its a null value

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False

In [21]:
cars.isna().sum() #it gives the sum of null values or count of null values in the columns along with the column names

manufacturer    0
mpg             0
cyl             0
disp            0
hp              0
drat            0
wt              0
qsec            0
vs              0
am              0
gear            0
carb            0
dtype: int64

In [22]:
cars.info() #it gives overall info of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   manufacturer  32 non-null     object
 1   mpg           32 non-null     float64
 2   cyl           32 non-null     int64
 3   disp          32 non-null     float64
 4   hp            32 non-null     int64
 5   drat          32 non-null     float64
 6   wt            32 non-null     float64
 7   qsec          32 non-null     float64
 8   vs            32 non-null     int64
 9   am            32 non-null     int64
 10  gear          32 non-null     int64
 11  carb          32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

In [23]:
cars.duplicated().sum()

0

In [24]:
cars.manufacturer #series data (only one column)

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: manufacturer, dtype: object

In [26]:
cars['manufacturer']

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: manufacturer, dtype: object

In [27]:
cars[['manufacturer']]#this is dataframe has both rows and column names

           manufacturer
0             Mazda RX4
1         Mazda RX4 Wag
2            Datsun 710
3        Hornet 4 Drive
4     Hornet Sportabout
5               Valiant
6            Duster 360
7             Merc 240D
8              Merc 230
9              Merc 280
10            Merc 280C
11           Merc 450SE
12           Merc 450SL
13          Merc 450SLC
14   Cadillac Fleetwood
15  Lincoln Continental
16    Chrysler Imperial
17             Fiat 128
18          Honda Civic
19       Toyota Corolla
20        Toyota Corona
21     Dodge Challenger
22          AMC Javelin
23           Camaro Z28
24     Pontiac Firebird
25            Fiat X1-9
26        Porsche 914-2
27         Lotus Europa
28       Ford Pantera L
29         Ferrari Dino
30        Maserati Bora
31           Volvo 142E

In [31]:
cars[['manufacturer','hp','gear','vs']] #one bracket one dimension, 2 brackets 2 dimensional data

           manufacturer   hp  gear  vs
0             Mazda RX4  110     4   0
1         Mazda RX4 Wag  110     4   0
2            Datsun 710   93     4   1
3        Hornet 4 Drive  110     3   1
4     Hornet Sportabout  175     3   0
5               Valiant  105     3   1
6            Duster 360  245     3   0
7             Merc 240D   62     4   1
8              Merc 230   95     4   1
9              Merc 280  123     4   1
10            Merc 280C  123     4   1
11           Merc 450SE  180     3   0
12           Merc 450SL  180     3   0
13          Merc 450SLC  180     3   0
14   Cadillac Fleetwood  205     3   0
15  Lincoln Continental  215     3   0
16    Chrysler Imperial  230     3   0
17             Fiat 128   66     4   1
18          Honda Civic   52     4   1
19       Toyota Corolla   65     4   1
20        Toyota Corona   97     3   1
21     Dodge Challenger  150     3   0
22          AMC Javelin  150     3   0
23           Camaro Z28  245     3   0
24     Pontiac Firebird  175     3   0
25            Fiat X1-9   66     4   1
26        Porsche 914-2   91     5   0
27         Lotus Europa  113     5   1
28       Ford Pantera L  264     5   0
29         Ferrari Dino  175     5   0
30        Maserati Bora  335     5   0
31           Volvo 142E  109     4   1

In [32]:
cars['half_qsec']=cars['qsec']/2

In [34]:
cars['drat']=cars['drat']+10
cars

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,half_qsec
0,Mazda RX4,21.0,6,160.0,110,13.90,2.620,16.46,0,1,4,4,8.230
1,Mazda RX4 Wag,21.0,6,160.0,110,13.90,2.875,17.02,0,1,4,4,8.510
2,Datsun 710,22.8,4,108.0,93,13.85,2.320,18.61,1,1,4,1,9.305
3,Hornet 4 Drive,21.4,6,258.0,110,13.08,3.215,19.44,1,0,3,1,9.720
4,Hornet Sportabout,18.7,8,360.0,175,13.15,3.440,17.02,0,0,3,2,8.510
5,Valiant,18.1,6,225.0,105,12.76,3.460,20.22,1,0,3,1,10.110
6,Duster 360,14.3,8,360.0,245,13.21,3.570,15.84,0,0,3,4,7.920
7,Merc 240D,24.4,4,146.7,62,13.69,3.190,20.00,1,0,4,2,10.000
8,Merc 230,22.8,4,140.8,95,13.92,3.150,22.90,1,0,4,2,11.450
9,Merc 280,19.2,6,167.6,123,13.92,3.440,18.30,1,0,4,4,9.150
10,Merc 280C,17.8,6,167.6,123,13.92,3.440,18.90,1,0,4,4,9.450
11,Merc 450SE,16.4,8,275.8,180,13.07,4.070,17.40,0,0,3,3,8.700
12,Merc 450SL,17.3,8,275.8,180,13.07,3.730,17.60,0,0,3,3,8.800
13,Merc 450SLC,15.2,8,275.8,180,13.07,3.780,18.00,0,0,3,3,9.000
14,Cadillac Fleetwood,10.4,8,472.0,205,12.93,5.250,17.98,0,0,3,4,8.990
15,Lincoln Continental,10.4,8,460.0,215,13.00,5.424,17.82,0,0,3,4,8.910
16,Chrysler Imperial,14.7,8,440.0,230,13.23,5.345,17.42,0,0,3,4,8.710
17,Fiat 128,32.4,4,78.7,66,14.08,2.200,19.47,1,1,4,1,9.735
18,Honda Civic,30.4,4,75.7,52,14.93,1.615,18.52,1,1,4,2,9.260
19,Toyota Corolla,33.9,4,71.1,65,14.22,1.835,19.90,1,1,4,1,9.950
20,Toyota Corona,21.5,4,120.1,97,13.70,2.465,20.01,1,0,3,1,10.005
21,Dodge Challenger,15.5,8,318.0,150,12.76,3.520,16.87,0,0,3,2,8.435
22,AMC Javelin,15.2,8,304.0,150,13.15,3.435,17.30,0,0,3,2,8.650
23,Camaro Z28,13.3,8,350.0,245,13.73,3.840,15.41,0,0,3,4,7.705
24,Pontiac Firebird,19.2,8,400.0,175,13.08,3.845,17.05,0,0,3,2,8.525
25,Fiat X1-9,27.3,4,79.0,66,14.08,1.935,18.90,1,1,4,1,9.450
26,Porsche 914-2,26.0,4,120.3,91,14.43,2.140,16.70,0,1,5,2,8.350
27,Lotus Europa,30.4,4,95.1,113,13.77,1.513,16.90,1,1,5,2,8.450
28,Ford Pantera L,15.8,8,351.0,264,14.22,3.170,14.50,0,1,5,4,7.250
29,Ferrari Dino,19.7,6,145.0,175,13.62,2.770,15.50,0,1,5,6,7.750
30,Maserati Bora,15.0,8,301.0,335,13.54,3.570,14.60,0,1,5,8,7.300
31,Volvo 142E,21.4,4,121.0,109,14.11,2.780,18.60,1,1,4,2,9.300

In [35]:
del cars['half_qsec']
cars

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,13.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,13.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,13.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,13.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,13.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,12.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,13.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,13.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,13.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,13.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,13.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,13.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,13.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,13.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,12.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,13.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,13.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,14.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,14.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,14.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,13.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,12.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,13.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,13.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,13.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,14.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,14.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,13.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,14.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,13.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,13.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,14.11,2.780,18.60,1,1,4,2

In [41]:
cars.drop(columns=['wt','am','carb'])

           manufacturer   mpg  cyl   disp   hp   drat   qsec  vs  gear
0             Mazda RX4  21.0    6  160.0  110  13.90  16.46   0     4
1         Mazda RX4 Wag  21.0    6  160.0  110  13.90  17.02   0     4
2            Datsun 710  22.8    4  108.0   93  13.85  18.61   1     4
3        Hornet 4 Drive  21.4    6  258.0  110  13.08  19.44   1     3
4     Hornet Sportabout  18.7    8  360.0  175  13.15  17.02   0     3
5               Valiant  18.1    6  225.0  105  12.76  20.22   1     3
6            Duster 360  14.3    8  360.0  245  13.21  15.84   0     3
7             Merc 240D  24.4    4  146.7   62  13.69  20.00   1     4
8              Merc 230  22.8    4  140.8   95  13.92  22.90   1     4
9              Merc 280  19.2    6  167.6  123  13.92  18.30   1     4
10            Merc 280C  17.8    6  167.6  123  13.92  18.90   1     4
11           Merc 450SE  16.4    8  275.8  180  13.07  17.40   0     3
12           Merc 450SL  17.3    8  275.8  180  13.07  17.60   0     3
13          Merc 450SLC  15.2    8  275.8  180  13.07  18.00   0     3
14   Cadillac Fleetwood  10.4    8  472.0  205  12.93  17.98   0     3
15  Lincoln Continental  10.4    8  460.0  215  13.00  17.82   0     3
16    Chrysler Imperial  14.7    8  440.0  230  13.23  17.42   0     3
17             Fiat 128  32.4    4   78.7   66  14.08  19.47   1     4
18          Honda Civic  30.4    4   75.7   52  14.93  18.52   1     4
19       Toyota Corolla  33.9    4   71.1   65  14.22  19.90   1     4
20        Toyota Corona  21.5    4  120.1   97  13.70  20.01   1     3
21     Dodge Challenger  15.5    8  318.0  150  12.76  16.87   0     3
22          AMC Javelin  15.2    8  304.0  150  13.15  17.30   0     3
23           Camaro Z28  13.3    8  350.0  245  13.73  15.41   0     3
24     Pontiac Firebird  19.2    8  400.0  175  13.08  17.05   0     3
25            Fiat X1-9  27.3    4   79.0   66  14.08  18.90   1     4
26        Porsche 914-2  26.0    4  120.3   91  14.43  16.70   0     5
27         Lotus Europa  30.4    4   95.1  113  13.77  16.90   1     5
28       Ford Pantera L  15.8    8  351.0  264  14.22  14.50   0     5
29         Ferrari Dino  19.7    6  145.0  175  13.62  15.50   0     5
30        Maserati Bora  15.0    8  301.0  335  13.54  14.60   0     5
31           Volvo 142E  21.4    4  121.0  109  14.11  18.60   1     4

In [44]:
cars.drop(['wt','am','carb'],axis=1,inplace=True) 
#0 axis always represents row and 1 axis always represents column
#inplace True= Delete the column permanently, inplace False= Delets the columns temporarily

In [45]:
cars['gear'].nunique() #displays tthe number of unique values in that column

3

In [46]:
cars['gear'].unique() #this gives what are the unique values in the particular column

array([4, 3, 5], dtype=int64)

In [57]:
#to check the number of unique values and what are unique values of all the columns
for i in cars.columns:
    print([i])
    print(cars[i].nunique())
    print(cars[i].unique())

['manufacturer']
32
['Mazda RX4' 'Mazda RX4 Wag' 'Datsun 710' 'Hornet 4 Drive'
 'Hornet Sportabout' 'Valiant' 'Duster 360' 'Merc 240D' 'Merc 230'
 'Merc 280' 'Merc 280C' 'Merc 450SE' 'Merc 450SL' 'Merc 450SLC'
 'Cadillac Fleetwood' 'Lincoln Continental' 'Chrysler Imperial' 'Fiat 128'
 'Honda Civic' 'Toyota Corolla' 'Toyota Corona' 'Dodge Challenger'
 'AMC Javelin' 'Camaro Z28' 'Pontiac Firebird' 'Fiat X1-9' 'Porsche 914-2'
 'Lotus Europa' 'Ford Pantera L' 'Ferrari Dino' 'Maserati Bora'
 'Volvo 142E']
['mpg']
25
[21.  22.8 21.4 18.7 18.1 14.3 24.4 19.2 17.8 16.4 17.3 15.2 10.4 14.7
 32.4 30.4 33.9 21.5 15.5 13.3 27.3 26.  15.8 19.7 15. ]
['cyl']
3
[6 4 8]
['disp']
27
[160.  108.  258.  360.  225.  146.7 140.8 167.6 275.8 472.  460.  440.
  78.7  75.7  71.1 120.1 318.  304.  350.  400.   79.  120.3  95.1 351.
 145.  301.  121. ]
['hp']
22
[110  93 175 105 245  62  95 123 180 205 215 230  66  52  65  97 150  91
 113 264 335 109]
['drat']
22
[13.9  13.85 13.08 13.15 12.76 13.21 13.69 13.92 13.07 12.93 13.   13.23
 14.08 14.93 14.22 13.7  13.73 14.43 13.77 13.62 13.54 14.11]
['qsec']
30
[16.46 17.02 18.61 19.44 20.22 15.84 20.   22.9  18.3  18.9  17.4  17.6
 18.   17.98 17.82 17.42 19.47 18.52 19.9  20.01 16.87 17.3  15.41 17.05
 16.7  16.9  14.5  15.5  14.6  18.6 ]
['vs']
2
[0 1]
['gear']
3
[4 3 5]

In [59]:
cars

           manufacturer   mpg  cyl   disp   hp   drat   qsec  vs  gear
0             Mazda RX4  21.0    6  160.0  110  13.90  16.46   0     4
1         Mazda RX4 Wag  21.0    6  160.0  110  13.90  17.02   0     4
2            Datsun 710  22.8    4  108.0   93  13.85  18.61   1     4
3        Hornet 4 Drive  21.4    6  258.0  110  13.08  19.44   1     3
4     Hornet Sportabout  18.7    8  360.0  175  13.15  17.02   0     3
5               Valiant  18.1    6  225.0  105  12.76  20.22   1     3
6            Duster 360  14.3    8  360.0  245  13.21  15.84   0     3
7             Merc 240D  24.4    4  146.7   62  13.69  20.00   1     4
8              Merc 230  22.8    4  140.8   95  13.92  22.90   1     4
9              Merc 280  19.2    6  167.6  123  13.92  18.30   1     4
10            Merc 280C  17.8    6  167.6  123  13.92  18.90   1     4
11           Merc 450SE  16.4    8  275.8  180  13.07  17.40   0     3
12           Merc 450SL  17.3    8  275.8  180  13.07  17.60   0     3
13          Merc 450SLC  15.2    8  275.8  180  13.07  18.00   0     3
14   Cadillac Fleetwood  10.4    8  472.0  205  12.93  17.98   0     3
15  Lincoln Continental  10.4    8  460.0  215  13.00  17.82   0     3
16    Chrysler Imperial  14.7    8  440.0  230  13.23  17.42   0     3
17             Fiat 128  32.4    4   78.7   66  14.08  19.47   1     4
18          Honda Civic  30.4    4   75.7   52  14.93  18.52   1     4
19       Toyota Corolla  33.9    4   71.1   65  14.22  19.90   1     4
20        Toyota Corona  21.5    4  120.1   97  13.70  20.01   1     3
21     Dodge Challenger  15.5    8  318.0  150  12.76  16.87   0     3
22          AMC Javelin  15.2    8  304.0  150  13.15  17.30   0     3
23           Camaro Z28  13.3    8  350.0  245  13.73  15.41   0     3
24     Pontiac Firebird  19.2    8  400.0  175  13.08  17.05   0     3
25            Fiat X1-9  27.3    4   79.0   66  14.08  18.90   1     4
26        Porsche 914-2  26.0    4  120.3   91  14.43  16.70   0     5
27         Lotus Europa  30.4    4   95.1  113  13.77  16.90   1     5
28       Ford Pantera L  15.8    8  351.0  264  14.22  14.50   0     5
29         Ferrari Dino  19.7    6  145.0  175  13.62  15.50   0     5
30        Maserati Bora  15.0    8  301.0  335  13.54  14.60   0     5
31           Volvo 142E  21.4    4  121.0  109  14.11  18.60   1     4

**25th May 2025**

In [3]:
cars

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [8]:
#calculate avg,max,min,variance,standard deviation and total of mpg column

#Maximum
cars[['mpg']].max()

mpg    33.9
dtype: float64

In [9]:
#Minimum
cars[['mpg']].min()

mpg    10.4
dtype: float64

In [10]:
#Average or mean
cars[['mpg']].mean()

mpg    20.090625
dtype: float64

In [11]:
#Variance
cars[['mpg']].var()

mpg    36.324103
dtype: float64

In [14]:
#standard deviation
cars[['mpg']].std()

mpg    6.026948
dtype: float64

In [16]:
#sum or total
cars['mpg'].sum()

642.9000000000001

In [17]:
cars['cyl'].value_counts() #total count of unique values

cyl
8    14
4    11
6     7
Name: count, dtype: int64

In [6]:
#extract the records of 6 unique values of cyl cars along with there complete details
cars[cars['cyl']==6]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6

In [18]:
#extract the records whose hp is between 100 to 200
cars[(cars['hp']>=100) & (cars['hp']<=200)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [21]:
#extract the records whose hp is not between 100 to 200
cars[(cars['hp']<100) | (cars['hp']>200)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8

In [23]:
#extract cars with 4 gears and 1 carb
cars[(cars['gear']==4) & (cars['carb']==1)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1

In [24]:
#extract cars with disp between 100 to 200 with 5 gears
cars[(cars['disp']>=100) & (cars['disp']<=200)&(cars['gear']==5)]

     manufacturer   mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
26  Porsche 914-2  26.0    4  120.3   91  4.43  2.14  16.7   0   1     5     2
29   Ferrari Dino  19.7    6  145.0  175  3.62  2.77  15.5   0   1     5     6

In [31]:
#extract cars with either 10 to 20 qsec or vs should be 0
cars[((cars['qsec']>=10) & (cars['qsec']<=20))|(cars['vs']==0)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [32]:
#display each gear-wise maximum mileage
cars.groupby(by='gear')['mpg'].max()

gear
3    21.5
4    33.9
5    30.4
Name: mpg, dtype: float64